<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Migrations\Module'                        => __DIR__ . '/Module.php',
    'Migrations\Controller\IndexController' => __DIR__ . '/src/Migrations/Controller/IndexController.php',
    'MigrationsTest\Framework\TestCase'        => __DIR__ . '/tests/Migrations/Framework/TestCase.php',
    'MigrationsTest\SampleTest'                => __DIR__ . '/tests/Migrations/SampleTest.php',
);
